// services/recommendations.js
import API from "./api";

/**
 * Get all recommendations for the current user from their latest assessment.
 * These are the real recommendations generated by the AI/manual scorer
 * and stored as Recommendation documents linked to the assessment.
 */
export const getLatestRecommendations = async () => {
  try {
    const response = await API.get("/recommendations");
    return response.data;
  } catch (error) {
    console.error("Error fetching recommendations:", error);
    throw error;
  }
};

/**
 * Get training modules that are directly linked to the user's pending
 * recommendations via relatedTrainingModuleId.
 *
 * Flow:
 *   1. Fetch latest assessment (which has populated recommendationIds)
 *   2. Extract unique relatedTrainingModuleId values from pending recs
 *   3. Fetch those specific training modules
 *
 * This is what powers the "Recommended Priority" section in TrainingModules.
 */
export const getAssessmentLinkedModules = async () => {
  try {
    // Step 1: get latest assessment with populated recommendations
    const assessment = await API.get("/assessments/latest");
    const recommendations = assessment.data?.recommendationIds || [];

    if (recommendations.length === 0) return [];

    // Step 2: collect unique module IDs from pending/in_progress recs
    const moduleIds = [
      ...new Set(
        recommendations
          .filter(
            (rec) =>
              rec.relatedTrainingModuleId &&
              (rec.status === "pending" || rec.status === "in_progress")
          )
          .map((rec) =>
            typeof rec.relatedTrainingModuleId === "object"
              ? rec.relatedTrainingModuleId._id || rec.relatedTrainingModuleId
              : rec.relatedTrainingModuleId
          )
      ),
    ];

    if (moduleIds.length === 0) return [];

    // Step 3: fetch those modules by ID
    const params = new URLSearchParams();
    moduleIds.forEach((id) => params.append("ids", id));

    const modulesRes = await API.get(`/training/by-ids?${params.toString()}`);
    return modulesRes.data || [];
  } catch (error) {
    console.error("Error fetching assessment-linked modules:", error);
    // Graceful fallback — don't break the training page if this fails
    return [];
  }
};

/**
 * Get top N pending recommendations sorted by priority (critical → high → medium → low).
 * Used by the dashboard's Strategic Recommendations panel.
 */
export const getTopPendingRecommendations = async (limit = 3) => {
  try {
    const assessment = await API.get("/assessments/latest");
    const recommendations = assessment.data?.recommendationIds || [];

    const priorityOrder = { critical: 0, high: 1, medium: 2, low: 3 };

    return recommendations
      .filter((rec) => rec.status === "pending" || rec.status === "in_progress")
      .sort(
        (a, b) =>
          (priorityOrder[a.priority] ?? 4) - (priorityOrder[b.priority] ?? 4)
      )
      .slice(0, limit);
  } catch (error) {
    console.error("Error fetching top recommendations:", error);
    return [];
  }
};

/**
 * Mark a recommendation as completed or dismissed.
 */
export const updateRecommendationStatus = async (recId, status) => {
  try {
    const response = await API.patch(`/recommendations/${recId}`, { status });
    return response.data;
  } catch (error) {
    console.error("Error updating recommendation status:", error);
    throw error;
  }
};